export const demoUsers = [
  {
    firstName: 'John',
    lastName: 'Doe',
    username: 'jdoe87',
    authLevel: 3,
    jobTitle: 'Technical Lead',
    password: 'password123',
    pictureColour: '#F1416C',
  },
  {
    firstName: 'Jane',
    lastName: 'Doe',
    username: 'jdoe92',
    authLevel: 2,
    jobTitle: 'Scrum Master',
    password: 'password123',
    pictureColour: '#50CD89',
  },
  {
    firstName: 'Ross',
    lastName: 'Derby',
    username: 'rderby95',
    authLevel: 1,
    jobTitle: 'Software Developer',
    password: 'password123',
    pictureColour: '#7239EA',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Levy',
    username: 'charlotteL90',
    authLevel: 1,
    jobTitle: 'UI / UX Designer',
    password: 'password123',
    pictureColour: '#BD00FF',
  },
  {
    firstName: 'Gavin',
    lastName: 'Fuller',
    username: 'gfuller04',
    authLevel: 1,
    jobTitle: 'Senior Software Developer',
    password: 'password123',
    pictureColour: '#009EF7',
  },
];
